version: "3.9"

services:
    app:
        build:
            context: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        command: sh -c "python app.py"

        restart: always